name: Test PyPI Installation
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test-pypi-installation:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y build-essential libxml2 libxml2-dev zlib1g-dev python3-tk graphviz
        python -m pip install pip==20.0.2
        python -m pip install RCAEval[default]

    - name: Test
      run: python -m pytest tests/test.py::test_basic
